In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
import os

from google.colab import drive
from pathlib import Path
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/HMCPW/data/v2/pt_pathways-w2v-top200-v2.csv')

In [ ]:
df.shape

(508, 261)

In [ ]:
df.head()

,id,Hospital LOS,Mean HLOS,admission_disposition,age,sex,Std Dev,Hypertension,Chronic cardiac disease (not hypertension),N/A,...,hypocholesteremia,bronchitis,ischemic,sinusitis,eye,arthroplasty,carcinoma,nephropathy,syncope,cholesterol
0,1,21,1,1,74,1,1,1,0,1,...,-0.608767,-0.455254,-0.777694,-0.679012,-0.688976,-0.836226,-0.584153,-0.657582,-0.642037,-0.945593
1,2,5,0,1,61,0,0,1,0,1,...,0.291599,0.460366,0.602479,0.694491,0.585712,0.765486,0.723863,0.625036,0.848367,-0.070907
2,3,7,0,1,58,0,0,1,0,1,...,1.154339,1.140940,1.137694,1.416582,1.151307,1.127899,1.298754,1.006759,1.208086,-0.587492
3,4,9,0,1,94,1,0,1,0,1,...,0.293452,0.350910,0.714539,0.628227,0.653386,0.962031,0.902187,0.961290,1.108696,0.863767
4,5,9,0,1,91,1,0,1,1,1,...,-0.110882,-0.280716,-0.346717,-0.038715,-0.208690,0.006369,-0.082120,0.008698,0.027187,-1.669720

In [ ]:
df = df.drop(['id', 'Hospital LOS', 'Std Dev', 'Cancer'], axis = 1)

In [ ]:
df = df.drop(['reason_for_admission_Atypical pneumonia [J18.9]', 'reason_for_admission_Fever of unknown origin [R50.9]','reason_for_admission_Hypoxic [R09.0]','reason_for_admission_Myalgia [M79.19]','reason_for_admission_Tachypnea [R06.8]', 'reason_for_admission_Viral pneumonia [J12.9]'], axis = 1)

In [ ]:
df.shape

(508, 251)

In [ ]:
df.head()

,Mean HLOS,admission_disposition,age,sex,Hypertension,Chronic cardiac disease (not hypertension),N/A,Diabetes,History of cancer [now in remission],Other,...,hypocholesteremia,bronchitis,ischemic,sinusitis,eye,arthroplasty,carcinoma,nephropathy,syncope,cholesterol
0,1,1,74,1,1,0,1,1,0,1,...,-0.608767,-0.455254,-0.777694,-0.679012,-0.688976,-0.836226,-0.584153,-0.657582,-0.642037,-0.945593
1,0,1,61,0,1,0,1,0,0,1,...,0.291599,0.460366,0.602479,0.694491,0.585712,0.765486,0.723863,0.625036,0.848367,-0.070907
2,0,1,58,0,1,0,1,0,0,0,...,1.154339,1.140940,1.137694,1.416582,1.151307,1.127899,1.298754,1.006759,1.208086,-0.587492
3,0,1,94,1,1,0,1,0,0,1,...,0.293452,0.350910,0.714539,0.628227,0.653386,0.962031,0.902187,0.961290,1.108696,0.863767
4,0,1,91,1,1,1,1,1,0,1,...,-0.110882,-0.280716,-0.346717,-0.038715,-0.208690,0.006369,-0.082120,0.008698,0.027187,-1.669720

In [ ]:
X = df.drop(['Mean HLOS'], axis = 1)
y = df[['Mean HLOS']]

In [ ]:
X

,admission_disposition,age,sex,Hypertension,Chronic cardiac disease (not hypertension),N/A,Diabetes,History of cancer [now in remission],Other,Kidney disease,...,hypocholesteremia,bronchitis,ischemic,sinusitis,eye,arthroplasty,carcinoma,nephropathy,syncope,cholesterol
0,1,74,1,1,0,1,1,0,1,0,...,-0.608767,-0.455254,-0.777694,-0.679012,-0.688976,-0.836226,-0.584153,-0.657582,-0.642037,-0.945593
1,1,61,0,1,0,1,0,0,1,0,...,0.291599,0.460366,0.602479,0.694491,0.585712,0.765486,0.723863,0.625036,0.848367,-0.070907
2,1,58,0,1,0,1,0,0,0,0,...,1.154339,1.140940,1.137694,1.416582,1.151307,1.127899,1.298754,1.006759,1.208086,-0.587492
3,1,94,1,1,0,1,0,0,1,0,...,0.293452,0.350910,0.714539,0.628227,0.653386,0.962031,0.902187,0.961290,1.108696,0.863767
4,1,91,1,1,1,1,1,0,1,0,...,-0.110882,-0.280716,-0.346717,-0.038715,-0.208690,0.006369,-0.082120,0.008698,0.027187,-1.669720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,1,74,0,0,0,1,0,0,1,0,...,-0.943641,-1.070204,-1.097203,-0.936481,-0.909164,-0.760367,-0.815774,-0.532641,-0.666101,0.331116
504,1,81,1,1,0,1,1,0,1,0,...,-0.065708,-0.147289,-0.339156,-0.376654,-0.392597,-0.489151,-0.504224,-0.469547,-0.609787,0.336431
505,1,74,1,1,0,1,0,0,1,0,...,-0.333385,-0.283479,-0.262611,-0.185571,-0.235554,-0.359282,-0.229991,-0.224896,-0.370747,0.996076
506,1,48,0,0,0,1,0,0,0,0,...,-0.564160,-0.591474,-0.769318,-0.744085,-0.646460,-0.849264,-0.771065,-0.614668,-0.748871,-0.783317
507,1,73,1,0,0,1,0,0,0,0,...,-0.524788,-0.293471,-0.364817,-0.372185,-0.226680,-0.179958,-0.186778,0.029016,-0.132643,-0.850836

In [ ]:
y

     Mean HLOS
0            1
1            0
2            0
3            0
4            0
..         ...
503          1
504          1
505          0
506          0
507          0

[508 rows x 1 columns]

# Logistic

In [ ]:
model = LogisticRegression(max_iter=1000)

In [ ]:
# CV just for trainig
cv_score_lr = cross_val_score(model, X, y, cv = 10)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
print(cv_score_lr)

[0.58823529 0.62745098 0.54901961 0.64705882 0.68627451 0.66666667
 0.68627451 0.60784314 0.58       0.7       ]

In [ ]:
mean_cv_score_lr = sum(cv_score_lr)/len(cv_score_lr)
mean_cv_score_lr = mean_cv_score_lr*100
mean_cv_score_lr = round(mean_cv_score_lr, 2)
print(mean_cv_score_lr)

63.39

# SVM *Classifier*

In [ ]:
from sklearn.svm import SVC

In [ ]:
#Accuracy in test data
cv_score_svc = cross_val_score(SVC(kernel='linear'), X, y, cv = 10)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
print(cv_score_svc)

[0.60784314 0.60784314 0.56862745 0.64705882 0.64705882 0.66666667
 0.62745098 0.62745098 0.6        0.62      ]

In [ ]:
mean_cv_score_svc = sum(cv_score_svc)/len(cv_score_svc)
mean_cv_score_svc = mean_cv_score_svc*100
mean_cv_score_svc = round(mean_cv_score_svc, 2)
print(mean_cv_score_svc)

62.2

# Random Forest

```
# This is formatted as code
```

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
random = RandomForestClassifier()

In [ ]:
cv_score_rfc = cross_val_score(random, X, y, cv = 10)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

In [ ]:
print(cv_score_rfc)

[0.68627451 0.68627451 0.64705882 0.66666667 0.68627451 0.66666667
 0.7254902  0.68627451 0.64       0.7       ]

In [ ]:
mean_cv_score_rfc = sum(cv_score_rfc)/len(cv_score_rfc)
mean_cv_score_rfc = mean_cv_score_rfc*100
mean_cv_score_rfc = round(mean_cv_score_rfc, 2)
print(mean_cv_score_rfc)

67.91

# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
cv_score_knn = cross_val_score(KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2), X, y, cv = 10)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [ ]:
print(cv_score_knn)

[0.68627451 0.66666667 0.56862745 0.70588235 0.66666667 0.68627451
 0.68627451 0.66666667 0.66       0.62      ]

In [ ]:
mean_cv_score_knn = sum(cv_score_knn)/len(cv_score_knn)
mean_cv_score_knn = mean_cv_score_knn*100
mean_cv_score_knn = round(mean_cv_score_knn, 2)
print(mean_cv_score_knn)

66.13