In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from sklearn import metrics

import os
from google.colab import drive
from pathlib import Path
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/HMCPW/data/v2/pt_pathways-w2v-top200-v2.csv')

In [ ]:
df.shape

(508, 261)

In [ ]:
df.head()

,id,Hospital LOS,Mean HLOS,admission_disposition,age,sex,Std Dev,Hypertension,Chronic cardiac disease (not hypertension),N/A,...,hypocholesteremia,bronchitis,ischemic,sinusitis,eye,arthroplasty,carcinoma,nephropathy,syncope,cholesterol
0,1,21,1,1,74,1,1,1,0,1,...,-0.608767,-0.455254,-0.777694,-0.679012,-0.688976,-0.836226,-0.584153,-0.657582,-0.642037,-0.945593
1,2,5,0,1,61,0,0,1,0,1,...,0.291599,0.460366,0.602479,0.694491,0.585712,0.765486,0.723863,0.625036,0.848367,-0.070907
2,3,7,0,1,58,0,0,1,0,1,...,1.154339,1.140940,1.137694,1.416582,1.151307,1.127899,1.298754,1.006759,1.208086,-0.587492
3,4,9,0,1,94,1,0,1,0,1,...,0.293452,0.350910,0.714539,0.628227,0.653386,0.962031,0.902187,0.961290,1.108696,0.863767
4,5,9,0,1,91,1,0,1,1,1,...,-0.110882,-0.280716,-0.346717,-0.038715,-0.208690,0.006369,-0.082120,0.008698,0.027187,-1.669720

In [ ]:
df = df.drop(['id', 'Std Dev', 'Cancer', 'Mean HLOS'], axis = 1)

In [ ]:
df= df.drop(['reason_for_admission_Atypical pneumonia [J18.9]', 'reason_for_admission_Fever of unknown origin [R50.9]','reason_for_admission_Hypoxic [R09.0]','reason_for_admission_Myalgia [M79.19]','reason_for_admission_Tachypnea [R06.8]', 'reason_for_admission_Viral pneumonia [J12.9]'], axis = 1)

In [ ]:
df.shape

(508, 251)

In [ ]:
X = df.drop(['Hospital LOS'], axis = 1)
y = df[['Hospital LOS']]

In [ ]:
X

,admission_disposition,age,sex,Hypertension,Chronic cardiac disease (not hypertension),N/A,Diabetes,History of cancer [now in remission],Other,Kidney disease,...,hypocholesteremia,bronchitis,ischemic,sinusitis,eye,arthroplasty,carcinoma,nephropathy,syncope,cholesterol
0,1,74,1,1,0,1,1,0,1,0,...,-0.608767,-0.455254,-0.777694,-0.679012,-0.688976,-0.836226,-0.584153,-0.657582,-0.642037,-0.945593
1,1,61,0,1,0,1,0,0,1,0,...,0.291599,0.460366,0.602479,0.694491,0.585712,0.765486,0.723863,0.625036,0.848367,-0.070907
2,1,58,0,1,0,1,0,0,0,0,...,1.154339,1.140940,1.137694,1.416582,1.151307,1.127899,1.298754,1.006759,1.208086,-0.587492
3,1,94,1,1,0,1,0,0,1,0,...,0.293452,0.350910,0.714539,0.628227,0.653386,0.962031,0.902187,0.961290,1.108696,0.863767
4,1,91,1,1,1,1,1,0,1,0,...,-0.110882,-0.280716,-0.346717,-0.038715,-0.208690,0.006369,-0.082120,0.008698,0.027187,-1.669720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,1,74,0,0,0,1,0,0,1,0,...,-0.943641,-1.070204,-1.097203,-0.936481,-0.909164,-0.760367,-0.815774,-0.532641,-0.666101,0.331116
504,1,81,1,1,0,1,1,0,1,0,...,-0.065708,-0.147289,-0.339156,-0.376654,-0.392597,-0.489151,-0.504224,-0.469547,-0.609787,0.336431
505,1,74,1,1,0,1,0,0,1,0,...,-0.333385,-0.283479,-0.262611,-0.185571,-0.235554,-0.359282,-0.229991,-0.224896,-0.370747,0.996076
506,1,48,0,0,0,1,0,0,0,0,...,-0.564160,-0.591474,-0.769318,-0.744085,-0.646460,-0.849264,-0.771065,-0.614668,-0.748871,-0.783317
507,1,73,1,0,0,1,0,0,0,0,...,-0.524788,-0.293471,-0.364817,-0.372185,-0.226680,-0.179958,-0.186778,0.029016,-0.132643,-0.850836

In [ ]:
y

     Hospital LOS
0              21
1               5
2               7
3               9
4               9
..            ...
503            13
504            19
505             9
506             7
507             5

[508 rows x 1 columns]

# Model Training

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 12, shuffle=True)

In [ ]:
print(X_train.shape, X_test.shape, y_train.shape)

(381, 250) (127, 250) (381, 1)

In [ ]:
regressor = LinearRegression()

In [ ]:
X_pred = regressor.fit(X_train, y_train)

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
print(y_pred)

[[ 1.61029364e+01]
 [ 4.66777746e+00]
 [-3.30241744e+00]
 [ 2.19917476e+01]
 [ 3.28670816e+00]
 [ 1.15350178e+01]
 [ 1.07958993e+01]
 [ 1.00438403e+01]
 [-3.15973444e+00]
 [ 5.12541051e+00]
 [ 2.52916243e+01]
 [ 1.88694017e+01]
 [-1.31340090e-01]
 [ 2.25994455e+01]
 [ 1.20721920e+01]
 [ 7.75307793e+00]
 [ 2.10724689e+01]
 [-2.40413289e+00]
 [ 1.04147942e+01]
 [ 2.67164597e+01]
 [ 2.98678849e+01]
 [-7.78468353e+00]
 [ 3.03507077e+01]
 [ 3.36401237e+01]
 [ 2.11300349e+01]
 [ 1.16995041e+01]
 [ 4.98222982e+00]
 [ 4.57826372e-01]
 [ 1.02538974e+01]
 [ 1.28030612e+01]
 [ 2.58183605e+00]
 [ 4.29193271e-01]
 [ 2.28612469e+01]
 [ 3.34954383e+01]
 [ 1.63047423e+01]
 [ 1.44006974e+01]
 [ 8.73626588e+00]
 [ 2.26315280e+01]
 [ 9.25408944e+00]
 [ 4.45056147e+00]
 [ 1.15620524e+01]
 [-5.09645332e+00]
 [ 4.54949588e+00]
 [ 1.43512513e+01]
 [-5.94862959e+00]
 [ 1.64890114e+01]
 [ 2.95115627e+01]
 [ 9.44716532e+00]
 [ 1.20824159e+01]
 [ 1.06113579e+01]
 [ 1.94361801e+01]
 [-4.69032517e+00]
 [ 1.82529728e+01]
 [-4.95178167e+00]
 [ 1.63236025e+01]
 [ 1.64464413e+01]
 [-2.02522679e+01]
 [ 2.59594612e+01]
 [ 5.27282512e+00]
 [ 7.13091141e+00]
 [-2.42907301e+00]
 [ 1.45492702e+01]
 [ 2.15753717e+00]
 [-2.14223513e+01]
 [ 1.72154520e+01]
 [ 1.40298957e+01]
 [ 9.51819430e+00]
 [ 2.40666391e+00]
 [ 2.35010156e+01]
 [ 2.91643998e+01]
 [ 2.76629713e+01]
 [ 4.72057004e+00]
 [ 4.15737655e+01]
 [-2.99067466e+00]
 [-4.53371670e+00]
 [-2.17236750e+00]
 [ 4.39805243e+00]
 [ 3.02991452e+01]
 [ 2.91831012e+01]
 [ 3.39035108e-02]
 [ 4.27098458e+01]
 [ 6.92841047e+00]
 [ 7.07483847e+00]
 [ 1.70942524e+01]
 [ 9.85235897e+00]
 [ 3.28162973e+01]
 [ 1.68822154e+01]
 [ 9.31677004e+00]
 [ 1.00470139e+01]
 [ 1.10142610e+01]
 [ 2.45012456e+01]
 [ 9.19509307e+00]
 [ 2.27891678e+01]
 [ 2.20208595e+01]
 [ 4.78049308e+00]
 [-5.86301857e-01]
 [-1.27070177e+01]
 [ 1.23671227e+01]
 [ 1.31740299e+01]
 [ 3.49370087e+01]
 [ 2.29297405e+01]
 [ 8.90968340e+00]
 [-5.49268137e+00]
 [ 2.70638188e+01]
 [ 1.31306258e+01]
 [ 4.05074207e+01]
 [ 6.24309565e+00]
 [ 1.15346887e+01]
 [ 1.33502041e+01]
 [ 5.29840690e+00]
 [ 6.12590162e+00]
 [-1.05077325e+01]
 [ 1.02932309e+01]
 [ 1.64893274e+01]
 [ 1.46495698e+01]
 [ 3.19524388e+01]
 [-3.15850030e+00]
 [ 1.49127919e+01]
 [ 1.33440393e+01]
 [ 5.93635991e+00]
 [ 2.42889182e+01]
 [ 7.28996459e+00]
 [-1.87136774e+00]
 [ 1.57271457e+01]
 [-4.70762723e+00]
 [ 4.59478271e+00]
 [ 6.03128869e+00]]

In [ ]:
r2_test_error = metrics.r2_score(y_test, y_pred)
print('R squared error for testing data:', r2_test_error)

R squared error for testing data: -0.7463928102165978

In [ ]:
from scipy.stats import linregress
import math
from sklearn.metrics import mean_squared_error
import statistics

In [ ]:
mse = mean_squared_error(y_test, y_pred)
rmse = math.sqrt(mse)
print(rmse)
print(mse)

16.73133576413357
279.93759645217506