In [65]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Lasso, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [145]:
xcel = "SMOTERegressionCases.xlsx"

# Load each sheet separately
df1 = pd.read_excel(xcel, sheet_name='Seed410_thr0.77_perc0.2')
df2 = pd.read_excel(xcel, sheet_name='Seed527_thr0.77_perc0.2')
df3 = pd.read_excel(xcel, sheet_name='Seed222_thr0.77_perc0.2')
df4 = pd.read_excel(xcel, sheet_name='Seed326_thr0.77_perc0.2')
df5 = pd.read_excel(xcel, sheet_name='Seed832_thr0.77_perc0.2')

# ## dropping column X, as it is unwanted
# df1 = df1.drop(['X'],axis=1)
# df2 = df2.drop(['X'],axis=1)
# df3 = df3.drop(['X'],axis=1)
# df4 = df4.drop(['X'],axis=1)
# df5 = df5.drop(['X'],axis=1)

In [146]:
df1.head()

,id,hospital_length_of_stay,age,sex,height,weight,smoking_history,previous_er_visit_within_14_days,admission_disposition,Hypertension,...,Respiractin,Immunity Advance,Vesicare,Zaxine,Quinine Sulfate,Desvenlafaxine,Glucosamine,Turmeric,Cogentin Tab,Elavil
0,289.0,0,55.0,1.0,165.000000,74.500000,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,18.0
1,233.0,0,65.0,1.0,166.911029,80.265922,1.0,0.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,10.0
2,309.0,0,40.0,0.0,166.911029,80.265922,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,6.0
3,377.0,0,56.0,0.0,166.911029,80.265922,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,15.0
4,126.0,0,82.0,0.0,166.911029,80.265922,0.0,0.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,8.0

In [147]:
df2.head()

,id,hospital_length_of_stay,age,sex,height,weight,smoking_history,previous_er_visit_within_14_days,admission_disposition,Hypertension,...,Respiractin,Immunity Advance,Vesicare,Zaxine,Quinine Sulfate,Desvenlafaxine,Glucosamine,Turmeric,Cogentin Tab,Elavil
0,207.0,0,64.0,1.0,185.000000,90.700000,0.0,0.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,9.0
1,18.0,0,87.0,0.0,166.000000,73.300000,0.0,0.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,5.0
2,161.0,0,49.0,0.0,166.911029,80.265922,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,2.0
3,106.0,0,91.0,1.0,166.911029,80.265922,0.0,0.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,9.0
4,107.0,0,78.0,0.0,158.000000,79.200000,0.0,0.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,16.0

In [137]:
df = pd.read_csv("../Datasets/new.csv")
df = df.drop("Unnamed: 0",axis=1)

df.rename(columns={' Chlorthalidone': 'Chlorthalidone.1'}, inplace=True)

df.columns = df.columns.str.strip()

df

,id,hospital_length_of_stay,age,sex,height,weight,smoking_history,previous_er_visit_within_14_days,admission_disposition,Hypertension,...,Respiractin,Immunity Advance,Vesicare,Zaxine,Quinine Sulfate,Desvenlafaxine,Glucosamine,Turmeric,Cogentin Tab,Elavil
0,1,21,74,1,166.911029,80.265922,0.0,0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,5,61,0,154.900000,73.600000,0.0,0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,7,58,0,166.911029,80.265922,0.0,0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,9,94,1,182.800000,66.200000,0.0,0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,9,91,1,166.911029,80.265922,1.0,0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,515,2,56,0,165.000000,72.600000,0.0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
502,516,13,74,0,166.911029,55.000000,0.0,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
503,517,19,81,1,158.000000,65.000000,0.0,1,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
504,519,9,74,1,166.911029,81.700000,0.0,1,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
505,12,9,76,0,162.000000,72.600000,0.0,0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [138]:
# Concatenate df with df1, df with df2, and df with df3 separately
df1 = pd.concat([df, df1], ignore_index=True)
df2 = pd.concat([df, df2], ignore_index=True)
df3 = pd.concat([df, df3], ignore_index=True)
df4 = pd.concat([df, df4], ignore_index=True)
df5 = pd.concat([df, df5], ignore_index=True)

In [148]:
# Randomize the rows by shuffling the index
df1 = df1.sample(frac=1).reset_index(drop=True)
df2 = df2.sample(frac=1).reset_index(drop=True)
df3 = df3.sample(frac=1).reset_index(drop=True)
df4 = df4.sample(frac=1).reset_index(drop=True)
df5 = df5.sample(frac=1).reset_index(drop=True)

In [150]:
df2

,id,hospital_length_of_stay,age,sex,height,weight,smoking_history,previous_er_visit_within_14_days,admission_disposition,Hypertension,...,Respiractin,Immunity Advance,Vesicare,Zaxine,Quinine Sulfate,Desvenlafaxine,Glucosamine,Turmeric,Cogentin Tab,Elavil
0,48.023178,0,59.081124,1.000000,160.023178,101.638420,0.000000,0.011589,0.011589,1.000000,...,0,0,0,0,0,0,0,0,0,39.0
1,347.234772,0,66.147842,0.000000,161.588476,61.762566,0.000000,0.617386,1.000000,0.000000,...,0,0,0,0,0,0,0,0,0,30.5
2,366.344124,0,82.785364,1.000000,171.105547,70.913655,0.000000,0.000000,1.000000,0.655876,...,0,0,0,0,0,0,0,0,0,44.0
3,311.578544,0,49.472798,0.000000,153.389885,68.248198,0.000000,0.684291,1.000000,0.315709,...,0,0,0,0,0,0,0,0,0,52.0
4,113.000000,0,64.000000,1.000000,198.000000,105.800000,1.000000,1.000000,1.000000,0.000000,...,0,0,0,0,0,0,0,0,0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,453.000000,0,73.000000,0.000000,149.900000,45.200000,0.000000,0.000000,0.000000,1.000000,...,0,0,0,0,0,0,0,0,0,10.0
514,277.000000,0,87.000000,1.000000,180.300000,100.500000,0.000000,0.000000,1.000000,1.000000,...,0,0,0,0,0,0,0,0,0,29.0
515,327.280837,0,83.725436,1.000000,168.119949,82.894590,0.379094,0.000000,1.000000,1.000000,...,0,0,0,0,0,0,0,0,0,25.0
516,89.000000,0,73.000000,0.000000,155.000000,50.900000,0.000000,0.000000,1.000000,0.000000,...,0,0,0,0,0,0,0,0,0,58.0
517,91.012397,0,82.002479,0.997521,172.965288,81.990082,0.000000,0.000000,0.002479,1.000000,...,0,0,0,0,0,0,0,0,0,38.5

### Scaling Age, Height and Weight

In [119]:
from sklearn.preprocessing import StandardScaler

columns_to_standardize = ['age', 'height', 'weight']

# Create a StandardScaler object
scaler = StandardScaler()

# Fit and transform the selected columns using the scaler
df1[columns_to_standardize] = scaler.fit_transform(df1[columns_to_standardize])
df2[columns_to_standardize] = scaler.fit_transform(df2[columns_to_standardize])
df3[columns_to_standardize] = scaler.fit_transform(df3[columns_to_standardize])
df4[columns_to_standardize] = scaler.fit_transform(df4[columns_to_standardize])
df5[columns_to_standardize] = scaler.fit_transform(df5[columns_to_standardize])

### Dropping unwanted columns

In [121]:
df1 = df1.drop(['id'],axis=1)
df2 = df2.drop(['id'],axis=1)
df3 = df3.drop(['id'],axis=1)
df4 = df4.drop(['id'],axis=1)
df5 = df5.drop(['id'],axis=1)

In [122]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error

def test_experiment_1(df):
    # Assuming 'df' has both features (X) and target (y) variables
    X = df.drop('hospital_length_of_stay', axis=1)  # Replace with actual column name
    y = df['hospital_length_of_stay']               # Replace with actual column name

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize the models with specified alpha values
    models = {
        'Lasso alpha 0.1': Lasso(alpha=0.1),
        'Lasso alpha 10': Lasso(alpha=10),
        'Ridge alpha 0.1': Ridge(alpha=0.1),
        'Ridge alpha 10': Ridge(alpha=10),
        'RandomForest': RandomForestRegressor(),
        'MLP': MLPRegressor(max_iter=500)  # Increase max_iter if necessary
    }
    
    # Dictionary to store the results
    results = {}

    # Loop over the models
    for name, model in models.items():
        # Fit the model on the training data
        model.fit(X_train, y_train)
        
        # Make predictions on the training data
        y_train_pred = model.predict(X_train)
        # Make predictions on the test data
        y_test_pred = model.predict(X_test)
        
        # Calculate MSE for training and test data
        train_mse = mean_squared_error(y_train, y_train_pred)
        test_mse = mean_squared_error(y_test, y_test_pred)
        
        # Store the results
        results[name] = {
            'Train MSE': train_mse,
            'Test MSE': test_mse
        }

    return results

# Run the test_experiment function on each dataset
results_df1 = test_experiment_1(df1)
results_df2 = test_experiment_1(df2)
results_df3 = test_experiment_1(df3)
results_df4 = test_experiment_1(df4)
results_df5 = test_experiment_1(df5)

# Create a dictionary to aggregate the results
aggregated_results = {}

# Add results from each dataset to the aggregated dictionary
for i, results in enumerate([results_df1, results_df2, results_df3, results_df4, results_df5], start=1):
    for model_name, metrics in results.items():
        if model_name not in aggregated_results:
            aggregated_results[model_name] = {
                'Train MSE': [],
                'Test MSE': []
            }
        aggregated_results[model_name]['Train MSE'].append(metrics['Train MSE'])
        aggregated_results[model_name]['Test MSE'].append(metrics['Test MSE'])

# Calculate mean and standard deviation for each model
final_results = {}

for model_name, mse_values in aggregated_results.items():
    avg_train_mse = round(sum(mse_values['Train MSE']) / len(mse_values['Train MSE']), 2)
    std_train_mse = round((sum((x - avg_train_mse) ** 2 for x in mse_values['Train MSE']) / len(mse_values['Train MSE'])) ** 0.5, 2)
    avg_test_mse = round(sum(mse_values['Test MSE']) / len(mse_values['Test MSE']), 2)
    std_test_mse = round((sum((x - avg_test_mse) ** 2 for x in mse_values['Test MSE']) / len(mse_values['Test MSE'])) ** 0.5, 2)
    
    # Combine mean and std into a single string
    final_results[model_name] = {
        'Train MSE (mean Â± std)': f"{avg_train_mse} Â± {std_train_mse}",
        'Test MSE (mean Â± std)': f"{avg_test_mse} Â± {std_test_mse}"
    }

# Convert final results to a DataFrame
results_df = pd.DataFrame(final_results).T  # Transpose for better readability

# Display the results
print(results_df)

/Users/asheshlalshrestha/anaconda3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/asheshlalshrestha/anaconda3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/asheshlalshrestha/anaconda3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/asheshlalshrestha/anaconda3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

                Train MSE (mean Â± std) Test MSE (mean Â± std)
Lasso alpha 0.1          131.62 Â± 1.07          163.3 Â± 9.96
Lasso alpha 10           262.16 Â± 4.45           298.9 Â± 7.3
Ridge alpha 0.1           18.17 Â± 0.77        132.25 Â± 10.14
Ridge alpha 10            81.93 Â± 1.77         121.86 Â± 5.66
RandomForest               7.33 Â± 0.31           63.0 Â± 3.59
MLP                        10.04 Â± 0.8        126.75 Â± 12.07

/Users/asheshlalshrestha/anaconda3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

In [125]:
results_df.to_csv('results_with_SMOGN.csv')

In [126]:
results_df

                Train MSE (mean Â± std) Test MSE (mean Â± std)
Lasso alpha 0.1          131.62 Â± 1.07          163.3 Â± 9.96
Lasso alpha 10           262.16 Â± 4.45           298.9 Â± 7.3
Ridge alpha 0.1           18.17 Â± 0.77        132.25 Â± 10.14
Ridge alpha 10            81.93 Â± 1.77         121.86 Â± 5.66
RandomForest               7.33 Â± 0.31           63.0 Â± 3.59
MLP                        10.04 Â± 0.8        126.75 Â± 12.07

In [127]:
def test_experiment_2(df):
    # Initialize models with specified alpha values
    models = {
        'Lasso alpha 0.1': Lasso(alpha=0.1),
        'Lasso alpha 10': Lasso(alpha=10),
        'Ridge alpha 0.1': Ridge(alpha=0.1),
        'Ridge alpha 10': Ridge(alpha=10),
        'RandomForest': RandomForestRegressor(),
        'MLP': MLPRegressor(max_iter=500)  # Increase max_iter if necessary
    }

    # Dictionary to store aggregated MSE results
    aggregated_results = {}

    # Loop to create 5 different subsets using different random states
    for random_state in range(5):
        # Perform the train-test split with varying random states
        X_train, X_test, y_train, y_test = train_test_split(
            df.drop('hospital_length_of_stay', axis=1),  # Drop the target column
            df['hospital_length_of_stay'],               # Target column
            test_size=0.2,                               # 20% for testing
            random_state=random_state                    # Use different random states
        )
        
        # Loop through each model
        for model_name, model in models.items():
            # Fit the model
            model.fit(X_train, y_train)
            
            # Predict on training and test data
            y_train_pred = model.predict(X_train)
            y_test_pred = model.predict(X_test)
            
            # Calculate MSE
            train_mse = mean_squared_error(y_train, y_train_pred)
            test_mse = mean_squared_error(y_test, y_test_pred)
            
            # Store results in aggregated_results dictionary
            if model_name not in aggregated_results:
                aggregated_results[model_name] = {
                    'Train MSE': [],
                    'Test MSE': []
                }
            aggregated_results[model_name]['Train MSE'].append(train_mse)
            aggregated_results[model_name]['Test MSE'].append(test_mse)

    # Calculate mean and std for each model's Train MSE and Test MSE
    final_results = {}

    for model_name, mse_values in aggregated_results.items():
        # Compute average and standard deviation for Train and Test MSE
        avg_train_mse = round(sum(mse_values['Train MSE']) / len(mse_values['Train MSE']), 2)
        std_train_mse = round((sum((x - avg_train_mse) ** 2 for x in mse_values['Train MSE']) / len(mse_values['Train MSE'])) ** 0.5, 2)
        avg_test_mse = round(sum(mse_values['Test MSE']) / len(mse_values['Test MSE']), 2)
        std_test_mse = round((sum((x - avg_test_mse) ** 2 for x in mse_values['Test MSE']) / len(mse_values['Test MSE'])) ** 0.5, 2)
        
        # Combine mean and std into a single string
        final_results[model_name] = {
            'Train MSE (mean Â± std)': f"{avg_train_mse} Â± {std_train_mse}",
            'Test MSE (mean Â± std)': f"{avg_test_mse} Â± {std_test_mse}"
        }

    # Convert final results to a DataFrame
    results_df = pd.DataFrame(final_results).T  # Transpose for better readability

    # Return the results
    return results_df

results_df = test_experiment_2(df)
results_df

                Train MSE (mean Â± std) Test MSE (mean Â± std)
Lasso alpha 0.1          104.39 Â± 4.52         128.8 Â± 26.56
Lasso alpha 10           140.32 Â± 6.64        119.46 Â± 26.15
Ridge alpha 0.1           10.97 Â± 1.85        260.86 Â± 25.58
Ridge alpha 10             76.86 Â± 4.8        135.97 Â± 24.62
RandomForest              19.68 Â± 1.24        116.95 Â± 21.91
MLP                     117.91 Â± 12.36        128.04 Â± 19.15